"""adding new tables owner 

Revision ID: 95332b0fca5c
Revises: 4115252bb84a
Create Date: 2020-10-28 21:52:25.677594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95332b0fca5c'
down_revision = '4115252bb84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
